name: xwidgets
description: "A new Flutter package project."
version: 1.0.0
repository: https://github.com/anonimeact/xwidgets.git

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  dropdown_search: ^6.0.2
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.9.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null

platforms:
  ? android
  ? ios
  ? linux
  ? macos
  ? web
  ? windows
